name: Update Map Data

on:
  push:
    paths:
    - data.xlsx
  schedule:
  - cron: '*/10 * * * *'
jobs:
    build:
    runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Install dependencies
    run: pip install pandas openpyxl
  - name: Convert Excel to JSON
    run: |
      python <<EOF
      print("convert here")
      EOF
  - name: Commit JSON
    run: |
      git config user.name "github-actions"
      git config user.email "actions@github.com"
      git add .
      git commit -m "update" || echo "no changes"
      git push
